name: Whitesource Prioritize Java with Maven & Github Issue comments

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      WS_APIKEY: ${{secrets.APIKEY}}
      WS_USERKEY: ${{secrets.USERKEY}}
      WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
      WS_PRODUCTNAME: GH_${{github.event.repository.name}}
      WS_PROJECTNAME: ${{github.event.repository.name}}_${{github.ref_name}}_Prioritize

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install -DskipTests=true
      - name: WhiteSource Unified Agent Scan
        env:
          WS_ENABLEIMPACTANALYSIS: true
          WS_RESOLVEALLDEPENDENCIES: false
          WS_MAVEN_RESOLVEDEPENDENCIES: true
          WS_MAVEN_AGGREGATEMODULES: true
          WS_FILESYSTEMSCAN: false
          WS_GENERATEPROJECTDETAILSJSON: true
        run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          echo Unified Agent downloaded successfully
          if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
            echo "Integrity Check Failed"
          else
            echo "Integrity Check Passed"
            WARFILE=$(find ./ -type f -wholename "*/target/*.war")
            echo $WARFILE will be added to appPath
            java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
          fi
