name: Renovate

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      RENOVATE_PLATFORM: 'github'
      RENOVATE_TOKEN: ${{secrets.RENOVATE_TOKEN}}
      LOG_LEVEL: 'debug'
      RENOVATE_REPOSITORIES: 'JoshRMendDemo/Java-Demo'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4.0.2
      - name: Run Renovate
        run: |
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name 'Renovate Bot'
          npx renovate
