name: Whitesource Prioritize Java with Maven & Github Issue comments

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      RENOVATE_PLATFORM: github
      RENOVATE_ENDPOINT: 'https://github.com/api/v3'
      RENOVATE_TOKEN: ${{secrets.RENOVATE_TOKEN}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4.0.2
      - name: Run Renovate
        run: |
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name 'Renovate Bot'
          npx renovate
