name: Renovate

on:
 schedule:
    - cron: '0 0 * * *'
 workflow_dispatch:

jobs:
  build:
    env:
      RENOVATE_PLATFORM: 'github'
      RENOVATE_TOKEN: ${{secrets.RENOVATE_TOKEN}}
      LOG_LEVEL: 'debug'
      RENOVATE_AUTODISCOVER: true
      RENOVATE_REQUIRE_CONFIG: 'ignored'
      RENOVATE_ONBOARDING: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4.0.2
      - name: Run Renovate
        run: |
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name 'Renovate Bot'
          npx renovate
